name: Deploy static content to Cloudflare Pages

on:
    # Runs on pushes targeting the default branch
    push:
        branches: ["main"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
        env:   #  设置Cloudflare项目名字与构建后的目录
            PROJECT_NAME: "atc-vp-gh-cf-docs"   # 项目名字
            BUILD_DIR: "./docs/.vitepress/dist"  # 构建后的目录
        name: Publish to Cloudflare Pages
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Node.js and npm
              uses: actions/setup-node@v3
              with:
                  node-version: '16'  # 你可以根据需要选择其他版本

            - name: Install dependencies
              run: |
                npm install
                npm install vitepress

            - name: Build documentation
              run: npm run docs:build

            - name: Deploy to Cloudflare Pages
              run: npx wrangler@3 pages deploy "${{ env.BUILD_DIR }}" --project-name="${{ env.PROJECT_NAME }}" --branch="main" --commit-dirty=true
              env:
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

